// Auth provider config — separated from auth.ts so the providers list
// can be unit-tested without pulling in the NextAuth runtime.

import GitHub from "next-auth/providers/github";
import Google from "next-auth/providers/google";
import Apple from "next-auth/providers/apple";
import type { NextAuthConfig } from "next-auth";

import { resolveRole, type Role } from "@/lib/roles";

const optional = (k: string) => (process.env[k] ? [process.env[k]!] : []);

// Provider list — each provider is enabled only when its required env
// vars are set, so local dev doesn't fail on missing Apple Team ID.
const providers: NextAuthConfig["providers"] = [];

if (process.env.AUTH_GITHUB_ID && process.env.AUTH_GITHUB_SECRET) {
  providers.push(
    GitHub({
      clientId: process.env.AUTH_GITHUB_ID,
      clientSecret: process.env.AUTH_GITHUB_SECRET,
    }),
  );
}

if (process.env.AUTH_GOOGLE_ID && process.env.AUTH_GOOGLE_SECRET) {
  providers.push(
    Google({
      clientId: process.env.AUTH_GOOGLE_ID,
      clientSecret: process.env.AUTH_GOOGLE_SECRET,
    }),
  );
}

if (process.env.AUTH_APPLE_ID && process.env.AUTH_APPLE_SECRET) {
  // Apple OIDC: AUTH_APPLE_SECRET is a JWT signed with the team's
  // private key, generated by NextAuth's helper or out-of-band. See
  // README — this is the most operator-heavy provider to wire up.
  providers.push(
    Apple({
      clientId: process.env.AUTH_APPLE_ID,
      clientSecret: process.env.AUTH_APPLE_SECRET,
    }),
  );
}

export const authConfig: NextAuthConfig = {
  providers,
  pages: { signIn: "/login" },
  trustHost: true,
  callbacks: {
    async jwt({ token, profile, account }) {
      // Persist provider-specific identity on first sign-in.
      if (account?.provider === "github" && profile && "login" in profile) {
        token.githubLogin = profile.login as string;
      }
      if (profile?.email && !token.email) {
        token.email = profile.email;
      }
      // Re-resolve role on every JWT refresh so env-config changes
      // take effect on next session refresh without re-login.
      const role: Role = resolveRole({
        githubLogin: token.githubLogin as string | undefined,
        email: token.email as string | undefined,
      });
      token.role = role;
      return token;
    },
    async session({ session, token }) {
      if (typeof token.githubLogin === "string") {
        session.user.githubLogin = token.githubLogin;
      }
      if (typeof token.role === "string") {
        session.user.role = token.role as Role;
      }
      return session;
    },
    authorized({ request, auth: session }) {
      // Top-gate auth check used by middleware. Per-route role gates
      // happen inside middleware.ts; this only enforces "logged-in".
      const path = request.nextUrl.pathname;
      const protectedPath =
        path.startsWith("/dashboard") ||
        path.startsWith("/agents") ||
        path.startsWith("/audit") ||
        path.startsWith("/capsules") ||
        path.startsWith("/policy") ||
        path.startsWith("/admin");
      if (protectedPath && !session) return false;
      return true;
    },
  },
};
