#!/usr/bin/env bash
# Stitch all 6 scenes + voiceover into a single 1080p MP4 ready for YouTube.
#
# Inputs (in ./scenes/):
#   scene-1-home.mp4       (~18s)
#   scene-3-proof.mp4      (~32s)
#   scene-5-uniswap.mp4    (~35s)
#   scene-6-outro.mp4      (~35s)
#   terminal-scenes.mp4    (~75s — covers Scene 2 + Scene 4 back-to-back, generated by vhs.tape)
#
# Plus:
#   ./voiceover.m4a        — the recorded voiceover audio
#
# Output:
#   ./output/final.mp4     (~3:00, 1080p, ≤50MB)

set -euo pipefail

cd "$(dirname "$0")"
mkdir -p output

# ─── Sanity: every required clip exists ────────────────────────────────
REQUIRED=(
  "scenes/scene-1-home.mp4"
  "scenes/terminal-scenes.mp4"
  "scenes/scene-3-proof.mp4"
  "scenes/scene-5-uniswap.mp4"
  "scenes/scene-6-outro.mp4"
  "voiceover.m4a"
)
missing=()
for f in "${REQUIRED[@]}"; do
  [ -f "$f" ] || missing+=("$f")
done
if [ ${#missing[@]} -gt 0 ]; then
  echo "❌ Missing files:"
  printf '   %s\n' "${missing[@]}"
  echo ""
  echo "Run record-browser-scenes.mjs (Step 2) and vhs (Step 1) first,"
  echo "then copy outputs here. See 0-record-checklist.md."
  exit 1
fi

# ─── Step A: split terminal-scenes.mp4 into Scene 2 (0-35s) + Scene 4 (35-75s) ───
# vhs.tape produces both back-to-back; we need Scene 2 to play 0:18-0:48 and
# Scene 4 to play 1:20-1:50 in the final cut, so split them out cleanly.
echo "▶ A. split terminal-scenes.mp4 into scene-2 + scene-4"
ffmpeg -y -i scenes/terminal-scenes.mp4 -ss 0 -t 30 -c copy scenes/scene-2-install.mp4
ffmpeg -y -i scenes/terminal-scenes.mp4 -ss 30 -t 30 -c copy scenes/scene-4-keeperhub.mp4

# ─── Step B: normalize every scene to identical codec / framerate / resolution ───
echo "▶ B. normalize all 6 scenes"
NORMALIZE_FLAGS="-vf scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:black,setsar=1 -r 30 -c:v libx264 -preset fast -crf 23 -pix_fmt yuv420p -an"
for s in 1-home 2-install 3-proof 4-keeperhub 5-uniswap 6-outro; do
  ffmpeg -y -i "scenes/scene-${s}.mp4" $NORMALIZE_FLAGS "scenes/_norm-${s}.mp4"
done

# ─── Step C: concat the 6 normalized scenes ────────────────────────────
echo "▶ C. concat scenes"
cat > scenes/_concat-list.txt <<EOF
file '_norm-1-home.mp4'
file '_norm-2-install.mp4'
file '_norm-3-proof.mp4'
file '_norm-4-keeperhub.mp4'
file '_norm-5-uniswap.mp4'
file '_norm-6-outro.mp4'
EOF

ffmpeg -y -f concat -safe 0 -i scenes/_concat-list.txt -c copy output/_video-only.mp4

# ─── Step D: mix in the voiceover ──────────────────────────────────────
# -shortest: trim to whichever is shorter (audio or video — usually audio is the
#   limiting factor since the video is paced to the script).
# -map 0:v:0 -map 1:a:0: explicit stream selection so we don't accidentally drop
#   the audio if voiceover is the second input.
echo "▶ D. mix voiceover into final"
ffmpeg -y \
  -i output/_video-only.mp4 \
  -i voiceover.m4a \
  -c:v copy \
  -c:a aac -b:a 192k -ac 2 \
  -map 0:v:0 -map 1:a:0 \
  -shortest \
  -movflags +faststart \
  output/final.mp4

# ─── Step E: cleanup intermediate files ────────────────────────────────
rm -f scenes/_norm-*.mp4 scenes/_concat-list.txt scenes/scene-2-install.mp4 scenes/scene-4-keeperhub.mp4 output/_video-only.mp4

# ─── Done ──────────────────────────────────────────────────────────────
echo ""
echo "✓ output/final.mp4 ready"
ls -lh output/final.mp4
echo ""
echo "Verify locally:"
echo "  open output/final.mp4"
echo ""
echo "If duration > 4 minutes, ETHGlobal disqualifies. Check:"
ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 output/final.mp4 \
  | awk '{ printf "  Duration: %d:%02d\n", int($1/60), int($1)%60 }'
echo ""
echo "If file size > 50 MB and you want it smaller:"
echo "  ffmpeg -i output/final.mp4 -c:v libx264 -crf 28 -c:a copy output/final-small.mp4"
