//! R14 P1 — tonic-based gRPC service implementation.
//!
//! Wraps the same [`AppState`] that backs the REST surface and reuses the
//! existing [`run_pipeline`] for `Decide`, `audit_count` / `audit_last`
//! for `Health`, and `audit_list` for `AuditChainStream`. No business
//! logic is duplicated — this is purely a wire-shape adapter.
//!
//! The generated code lives in `OUT_DIR/sbo3l.v1.rs`; see `build.rs`.
//! We re-export the generated types under `pb` for ergonomic use in
//! tests and the binary entrypoint.

// `tonic::Status` is ~176 bytes which trips `clippy::result_large_err`
// on every handler that returns `Result<_, Status>`. The pattern is
// idiomatic tonic and boxing every error would force an extra heap
// allocation on the hot path; we opt out at module scope rather than
// pollute each handler with a per-fn `#[allow]`.
#![allow(clippy::result_large_err)]

use std::pin::Pin;
use std::sync::Arc;
use std::time::Instant;

use tokio_stream::Stream;
use tonic::{Request, Response, Status};

use crate::{run_pipeline, AppInner, PaymentRequestResponse, PaymentStatus, Problem};
use sbo3l_core::receipt::Decision as ReceiptDecision;

/// The generated proto types and service traits. Re-exported as `pb`
/// so call sites read `pb::DecideRequest` etc.
///
/// Lints are silenced inside this module because the contents are
/// emitted by `tonic-build` / `prost-build` — clippy gripes about
/// generated docstrings (`doc_lazy_continuation`) and large `Err`
/// variants (`result_large_err`, fundamental to tonic's `Status`)
/// that we can't fix without forking codegen.
#[allow(clippy::doc_lazy_continuation)]
#[allow(clippy::result_large_err)]
#[allow(clippy::large_enum_variant)]
pub mod pb {
    // Generated by `tonic-build` from `proto/sbo3l.proto`.
    tonic::include_proto!("sbo3l.v1");
}

pub use pb::sbo3l_client::Sbo3lClient;
pub use pb::sbo3l_server::{Sbo3l, Sbo3lServer};

/// Concrete tonic service. Holds an `Arc<AppInner>` so RPCs share the
/// same storage / signers / metrics registry as the REST handlers.
#[derive(Clone)]
pub struct GrpcService {
    inner: Arc<AppInner>,
    started_at: Instant,
}

impl GrpcService {
    pub fn new(inner: Arc<AppInner>) -> Self {
        let started_at = inner.started_at;
        Self { inner, started_at }
    }

    /// Convenience for tests + the binary: build a `Sbo3lServer` ready
    /// to register on a tonic `Router::add_service` call.
    pub fn into_server(self) -> Sbo3lServer<Self> {
        Sbo3lServer::new(self)
    }
}

#[tonic::async_trait]
impl Sbo3l for GrpcService {
    async fn decide(
        &self,
        request: Request<pb::DecideRequest>,
    ) -> Result<Response<pb::DecideResponse>, Status> {
        let req = request.into_inner();
        // Parse the JSON body. A malformed request fails at the gRPC
        // boundary with INVALID_ARGUMENT — this mirrors the REST
        // surface returning HTTP 400 for bad JSON. We never reach
        // `run_pipeline` with an unparseable body.
        let body: serde_json::Value = serde_json::from_str(&req.aprp_json)
            .map_err(|e| Status::invalid_argument(format!("schema.malformed_json: {e}")))?;

        let pipeline_result = run_pipeline(&self.inner, body).await;
        match pipeline_result {
            Ok(resp) => Ok(Response::new(payment_response_to_proto(resp)?)),
            Err(problem) => Err(problem_to_status(problem)),
        }
    }

    async fn health(
        &self,
        _request: Request<pb::HealthRequest>,
    ) -> Result<Response<pb::HealthResponse>, Status> {
        let uptime_seconds = self.started_at.elapsed().as_secs();
        let storage = self
            .inner
            .storage
            .lock()
            .map_err(|_| Status::unavailable("storage_unreachable: mutex poisoned"))?;
        let length = storage
            .audit_count()
            .map_err(|e| Status::unavailable(format!("storage_unreachable: audit_count: {e}")))?;
        let head = storage
            .audit_last()
            .map_err(|e| Status::unavailable(format!("storage_unreachable: audit_last: {e}")))?
            .map(|ev| ev.event_hash)
            .unwrap_or_default();
        Ok(Response::new(pb::HealthResponse {
            status: "ok".to_string(),
            version: env!("CARGO_PKG_VERSION").to_string(),
            audit_chain_head: head,
            audit_chain_length: length,
            uptime_seconds,
        }))
    }

    type AuditChainStreamStream =
        Pin<Box<dyn Stream<Item = Result<pb::AuditChainEvent, Status>> + Send + 'static>>;

    async fn audit_chain_stream(
        &self,
        request: Request<pb::AuditChainRequest>,
    ) -> Result<Response<Self::AuditChainStreamStream>, Status> {
        let req = request.into_inner();
        let since_seq = req.since_seq;
        // Default page size: when the client passes zero we cap at
        // 1000 to keep the response bounded; production callers that
        // need the full chain can paginate via `since_seq`.
        let limit = if req.limit == 0 { 1000 } else { req.limit };

        // Materialise the slice up-front so we can drop the storage
        // mutex before yielding. This keeps the lock-hold window
        // short and avoids deadlocking with the REST handlers that
        // may run concurrently on the same `AppInner`.
        let events: Vec<sbo3l_core::audit::SignedAuditEvent> = {
            let storage = self
                .inner
                .storage
                .lock()
                .map_err(|_| Status::unavailable("storage_unreachable: mutex poisoned"))?;
            storage
                .audit_list()
                .map_err(|e| Status::internal(format!("audit.write_failed: audit_list: {e}")))?
        };

        let stream = async_stream::try_stream! {
            let mut emitted: u64 = 0;
            for ev in events.into_iter() {
                if ev.event.seq <= since_seq {
                    continue;
                }
                if emitted >= limit {
                    break;
                }
                emitted += 1;
                yield pb::AuditChainEvent {
                    seq: ev.event.seq,
                    event_id: ev.event.id,
                    event_hash: ev.event_hash,
                    prev_event_hash: ev.event.prev_event_hash,
                    event_type: ev.event.event_type,
                    ts: ev.event.ts.to_rfc3339(),
                };
            }
        };
        Ok(Response::new(Box::pin(stream)))
    }
}

/// Map a successful `PaymentRequestResponse` to its proto twin. The
/// signed `PolicyReceipt` is serialised as a JSON string — see the
/// proto file header for rationale (canonical-JSON signing means the
/// verifier needs the same bytes the server signed).
fn payment_response_to_proto(resp: PaymentRequestResponse) -> Result<pb::DecideResponse, Status> {
    let receipt_json = serde_json::to_string(&resp.receipt)
        .map_err(|e| Status::internal(format!("audit.serialization: receipt encode: {e}")))?;
    let status = match resp.status {
        PaymentStatus::AutoApproved => pb::PaymentStatus::AutoApproved,
        PaymentStatus::Rejected => pb::PaymentStatus::Rejected,
        PaymentStatus::RequiresHuman => pb::PaymentStatus::RequiresHuman,
    } as i32;
    let decision = match resp.decision {
        ReceiptDecision::Allow => pb::Decision::Allow,
        ReceiptDecision::Deny => pb::Decision::Deny,
        ReceiptDecision::RequiresHuman => pb::Decision::RequiresHuman,
    } as i32;
    Ok(pb::DecideResponse {
        status,
        decision,
        deny_code: resp.deny_code.unwrap_or_default(),
        matched_rule_id: resp.matched_rule_id.unwrap_or_default(),
        request_hash: resp.request_hash,
        policy_hash: resp.policy_hash,
        audit_event_id: resp.audit_event_id,
        receipt_json,
    })
}

/// Map a REST `Problem` (Status code + `code` string) to a tonic
/// `Status`. The original Problem `code` is preserved in
/// `Status::message` so callers can branch on `protocol.nonce_replay`
/// etc. without parsing arbitrary text.
///
/// HTTP → gRPC mapping rationale:
///
///   * 400 → `invalid_argument`. This covers schema failures, malformed
///     APRP, expired APRP, and idempotency-key shape errors.
///   * 401 / 403 → `unauthenticated` / `permission_denied`. The
///     gRPC scaffold doesn't yet wire auth (see `What NOT to ship` in
///     the task brief), but if a future revision adds it the mapping
///     is canonical.
///   * 409 → `already_exists`. Matches the `protocol.nonce_replay`
///     semantic — same nonce already seen.
///   * 5xx → `internal`. The Problem `code` distinguishes
///     `audit.write_failed` from `audit.signer_unavailable` etc.
fn problem_to_status(problem: Problem) -> Status {
    let detail = format!("{}: {}", problem.code, problem.detail);
    match problem.status {
        400 => Status::invalid_argument(detail),
        401 => Status::unauthenticated(detail),
        403 => Status::permission_denied(detail),
        404 => Status::not_found(detail),
        409 => Status::already_exists(detail),
        429 => Status::resource_exhausted(detail),
        503 => Status::unavailable(detail),
        _ => Status::internal(detail),
    }
}

#[cfg(test)]
mod tests {
    //! Direct unit tests for the gRPC service. These exercise the
    //! handler methods without going over the network — we construct
    //! the service, hand it a `tonic::Request`, and assert on the
    //! returned `tonic::Response` or `Status`.

    use super::*;
    use crate::{reference_policy, AppState};
    use sbo3l_storage::Storage;
    use serde_json::Value;
    use std::time::Duration;
    use tokio_stream::StreamExt;

    const APRP_GOLDEN: &str = include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../test-corpus/aprp/golden_001_minimal.json"
    ));

    fn make_service() -> GrpcService {
        let storage = Storage::open_in_memory().expect("in-memory storage");
        let state = AppState::new(reference_policy(), storage);
        GrpcService::new(state.0)
    }

    fn aprp_with_nonce(nonce: &str) -> String {
        let mut v: Value = serde_json::from_str(APRP_GOLDEN).unwrap();
        v["nonce"] = Value::String(nonce.to_string());
        serde_json::to_string(&v).unwrap()
    }

    #[tokio::test]
    async fn decide_happy_path_allows_under_reference_policy() {
        let svc = make_service();
        let req = Request::new(pb::DecideRequest {
            aprp_json: aprp_with_nonce("01HMG0CTPCH4VVRG0TVCH0001A"),
        });
        let resp = svc.decide(req).await.expect("decide ok").into_inner();
        assert_eq!(resp.status, pb::PaymentStatus::AutoApproved as i32);
        assert_eq!(resp.decision, pb::Decision::Allow as i32);
        assert!(resp.deny_code.is_empty());
        assert!(!resp.request_hash.is_empty());
        assert!(!resp.policy_hash.is_empty());
        assert!(!resp.audit_event_id.is_empty());
        // Receipt is a JSON-encoded PolicyReceipt; verify it parses
        // back into the typed struct.
        let parsed: sbo3l_core::receipt::PolicyReceipt =
            serde_json::from_str(&resp.receipt_json).expect("receipt json roundtrips");
        assert_eq!(parsed.agent_id, "research-agent-01");
    }

    #[tokio::test]
    async fn decide_replay_returns_already_exists() {
        let svc = make_service();
        let nonce = "01HMG0CTPCH4VVRG0TVCH0002B";
        // First request consumes the nonce.
        let _ = svc
            .decide(Request::new(pb::DecideRequest {
                aprp_json: aprp_with_nonce(nonce),
            }))
            .await
            .expect("first decide ok");
        // Second request with the same nonce hits the persistent
        // replay store and rejects.
        let err = svc
            .decide(Request::new(pb::DecideRequest {
                aprp_json: aprp_with_nonce(nonce),
            }))
            .await
            .expect_err("replay must fail");
        assert_eq!(err.code(), tonic::Code::AlreadyExists);
        assert!(
            err.message().contains("protocol.nonce_replay"),
            "expected nonce_replay code, got: {}",
            err.message()
        );
    }

    #[tokio::test]
    async fn decide_invalid_json_returns_invalid_argument() {
        let svc = make_service();
        let err = svc
            .decide(Request::new(pb::DecideRequest {
                aprp_json: "not-json{".to_string(),
            }))
            .await
            .expect_err("malformed json must fail");
        assert_eq!(err.code(), tonic::Code::InvalidArgument);
        assert!(err.message().contains("schema.malformed_json"));
    }

    #[tokio::test]
    async fn decide_schema_violation_returns_invalid_argument() {
        let svc = make_service();
        // An empty object has no required APRP fields — schema
        // validation rejects it before we touch the pipeline.
        let err = svc
            .decide(Request::new(pb::DecideRequest {
                aprp_json: "{}".to_string(),
            }))
            .await
            .expect_err("empty object must fail schema validation");
        assert_eq!(err.code(), tonic::Code::InvalidArgument);
    }

    #[tokio::test]
    async fn health_fresh_daemon_reports_zero_chain_length() {
        let svc = make_service();
        let resp = svc
            .health(Request::new(pb::HealthRequest {}))
            .await
            .expect("health ok")
            .into_inner();
        assert_eq!(resp.status, "ok");
        assert_eq!(resp.audit_chain_length, 0);
        assert!(resp.audit_chain_head.is_empty());
        assert_eq!(resp.version, env!("CARGO_PKG_VERSION"));
    }

    #[tokio::test]
    async fn health_after_one_request_reports_chain_growth() {
        let svc = make_service();
        let _ = svc
            .decide(Request::new(pb::DecideRequest {
                aprp_json: aprp_with_nonce("01HMG0CTPCH4VVRG0TVCH0003C"),
            }))
            .await
            .expect("decide ok");
        // Sleep 1.1s so uptime_seconds is provably non-zero — keeps
        // the assertion strict without a brittle "was the timer fast
        // enough" race.
        tokio::time::sleep(Duration::from_millis(1100)).await;
        let resp = svc
            .health(Request::new(pb::HealthRequest {}))
            .await
            .expect("health ok")
            .into_inner();
        assert_eq!(resp.audit_chain_length, 1);
        assert!(!resp.audit_chain_head.is_empty());
        assert!(resp.uptime_seconds >= 1);
    }

    #[tokio::test]
    async fn audit_chain_stream_emits_each_event_in_order() {
        let svc = make_service();
        for (i, nonce) in [
            "01HMG0CTPCH4VVRG0TVCH0010A",
            "01HMG0CTPCH4VVRG0TVCH0010B",
            "01HMG0CTPCH4VVRG0TVCH0010C",
        ]
        .iter()
        .enumerate()
        {
            svc.decide(Request::new(pb::DecideRequest {
                aprp_json: aprp_with_nonce(nonce),
            }))
            .await
            .unwrap_or_else(|e| panic!("decide #{i} failed: {e}"));
        }

        let resp = svc
            .audit_chain_stream(Request::new(pb::AuditChainRequest {
                since_seq: 0,
                limit: 0,
            }))
            .await
            .expect("stream ok")
            .into_inner();
        let collected: Vec<_> = resp
            .collect::<Vec<Result<pb::AuditChainEvent, Status>>>()
            .await;
        assert_eq!(collected.len(), 3, "must emit one event per decision");
        // Seqs are strictly increasing starting from 1.
        let seqs: Vec<u64> = collected.iter().map(|r| r.as_ref().unwrap().seq).collect();
        assert_eq!(seqs, vec![1, 2, 3]);
        // Chain linkage: each event's prev_event_hash matches the
        // previous event's event_hash, with the genesis hash for the
        // first row.
        let prev_hashes: Vec<&str> = collected
            .iter()
            .map(|r| r.as_ref().unwrap().prev_event_hash.as_str())
            .collect();
        assert_eq!(prev_hashes[0], sbo3l_core::audit::ZERO_HASH);
        for i in 1..collected.len() {
            let expected_prev = &collected[i - 1].as_ref().unwrap().event_hash;
            assert_eq!(
                prev_hashes[i],
                expected_prev,
                "event {i} prev_event_hash must equal event {} event_hash",
                i - 1
            );
        }
    }

    #[tokio::test]
    async fn audit_chain_stream_respects_since_seq_cursor() {
        let svc = make_service();
        for nonce in [
            "01HMG0CTPCH4VVRG0TVCH0020A",
            "01HMG0CTPCH4VVRG0TVCH0020B",
            "01HMG0CTPCH4VVRG0TVCH0020C",
        ] {
            svc.decide(Request::new(pb::DecideRequest {
                aprp_json: aprp_with_nonce(nonce),
            }))
            .await
            .expect("decide ok");
        }
        let resp = svc
            .audit_chain_stream(Request::new(pb::AuditChainRequest {
                since_seq: 1,
                limit: 0,
            }))
            .await
            .expect("stream ok")
            .into_inner();
        let collected: Vec<_> = resp
            .collect::<Vec<Result<pb::AuditChainEvent, Status>>>()
            .await;
        // Only seq=2 and seq=3 survive the since_seq=1 filter.
        assert_eq!(collected.len(), 2);
        assert_eq!(collected[0].as_ref().unwrap().seq, 2);
        assert_eq!(collected[1].as_ref().unwrap().seq, 3);
    }

    #[tokio::test]
    async fn audit_chain_stream_respects_limit() {
        let svc = make_service();
        for nonce in [
            "01HMG0CTPCH4VVRG0TVCH0030A",
            "01HMG0CTPCH4VVRG0TVCH0030B",
            "01HMG0CTPCH4VVRG0TVCH0030C",
        ] {
            svc.decide(Request::new(pb::DecideRequest {
                aprp_json: aprp_with_nonce(nonce),
            }))
            .await
            .expect("decide ok");
        }
        let resp = svc
            .audit_chain_stream(Request::new(pb::AuditChainRequest {
                since_seq: 0,
                limit: 2,
            }))
            .await
            .expect("stream ok")
            .into_inner();
        let collected: Vec<_> = resp
            .collect::<Vec<Result<pb::AuditChainEvent, Status>>>()
            .await;
        assert_eq!(collected.len(), 2, "limit=2 must cap the stream");
    }

    #[tokio::test]
    async fn problem_status_mapping_covers_documented_codes() {
        // Direct unit test of the mapping function — kept inline so
        // adding a new HTTP status code immediately surfaces a
        // missing arm in review.
        use crate::problem;
        let cases = &[
            (400, tonic::Code::InvalidArgument),
            (401, tonic::Code::Unauthenticated),
            (403, tonic::Code::PermissionDenied),
            (404, tonic::Code::NotFound),
            (409, tonic::Code::AlreadyExists),
            (429, tonic::Code::ResourceExhausted),
            (500, tonic::Code::Internal),
            (503, tonic::Code::Unavailable),
        ];
        for (http, grpc) in cases {
            let p = problem("test.case", *http, "title", "detail");
            assert_eq!(
                problem_to_status(p).code(),
                *grpc,
                "HTTP {http} must map to gRPC {grpc:?}"
            );
        }
    }
}
